### ISSUE TITLE
CLI file path output

### ISSUE THREAD

**Issue by TFK70** [atls/tools#201]
### Описание бага

В аутпуте команды `lint` (например) присутствуют пути до файлов, где возникла ошибка, но при этом нет возможности прокликать путь как ссылку через ctrl/command и перейти сразу к файлу

### Воспроизведение

Шаги для воспроизведения бага:

1. `yarn lint` на любом проекте, главное чтобы в аутпуте была ошибка
2. Видим, что пути до файлов не прокликиваются

### Ожидаемое поведение

Путь до файла можно прокликать как ссылку и перейти сразу к файлу

### Материалы

https://user-images.githubusercontent.com/62806448/150778005-6d2b34dd-978c-49f3-87f0-af911eb3e846.mov

### Данные окружения

- macOS Monterey
- Консоль IntelliJ Idea/Системная консоль

**Comment by TorinAsakura** [comment]
@TFK70 https://github.com/monstrs-lab/tools/blob/master/cli/cli-ui-eslint-result-component/src/eslint-result.component.tsx#L21 можешь убрать рилейтив, но, тогда испортится вид, или же можешь поправить relative links в idea или же просто поставить iterm2 как у нас, но в целом пох - спотлайт рулит
