### ISSUE TITLE
Добавить игнор в `formatter`

### ISSUE THREAD

**Issue by Nelfimov** [atls/tools#248]
### С чем связан запрос на фичу?

Игнорирование форматтерем чужого кода/легаси

### Расскажите как вы это себе видите

- [ ] Добавить в паттерн папку, напр. `legacy` - задача минимум
- [ ] Переписать `formatter` для чтения параметров проекта из корневого `package.json`

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Таске месяц. Закрыта за утратой актуальности.

**Comment by Amiditin** [comment]
@Nelfimov

Как я понял, смысл в том чтобы форматировать только измененые файлы? В документации [ignore](https://github.com/kaelzhang/node-ignore) я не нашел инфы про такие паттерны, + там написано 
> `ignore` only contains utility methods to filter paths according to the specified ignore rules, so
> - `ignore` never try to find out ignore rules by traversing directories or fetching from git configurations.
> - `ignore` don't cares about sub-modules of git projects.

Как вариант можно попробовать использовать [jest-changed-files](https://www.npmjs.com/package/jest-changed-files), или что то подобное, и заранее прокидывать только измененные файлы.
```ts
import {getChangedFilesForRoots} from 'jest-changed-files';

getChangedFilesForRoots(['/path/to/test'], {
  lastCommit: true,
  withAncestor: true,
}).then(files => {
  /*
  {
    repos: [],
    changedFiles: []
  }
  */
});
```

**Comment by Nelfimov** [comment]
Все проще - форматтер должен форматировать все кроме файлов/папок, попадающие в определенный паттерн.

Вот пример игноров для линтера и тайпчекера. Это прописывается в корневой `package.json` проекта:

```json
  "linterIgnorePatterns": [
    "app/*",
    "extension/*",
    "node/*",
    "power-up/*",
    "fork/*"
  ],
  "typecheckIgnorePatterns": [
    "app/*",
    "extension/*",
    "node/*",
    "power-up/*",
    "fork/*"
  ]
```

Сейчас в форматтере написано нечто подобное, однако оно не работает. Поэтому легкий и плохой вариант - захардкодить название папок для игнорирования, напр. `legacy`, либо сложный и отличный вариант - сделать аналогично линтеру и тайпчекеру.

**Comment by Amiditin** [comment]
@Nelfimov а изменения, которые вносятся в ['src'](https://github.com/atls/tools/tree/master/code/code-format/src) они сразу же применяются? или их нужно сбилдить, чтобы они заработали?

**Comment by Nelfimov** [comment]
@Amiditin если ты про тестирование, то можешь src или биол притянуть в любой проект, там в корне заменить code-format на локальный и тестить. 

Если ты готов к публикации и все работает, то делаешь пр. После релиза версия в npm обновится.

**Comment by Nelfimov** [comment]
@Amiditin дезинформировал тебя - code-format идет как зависимость для format plugin. Надо билдить yarn и его использовать в проектах.

**Comment by Amiditin** [comment]
@Nelfimov что то у меня не получается :/, можешь поподробней схему объяснить или мб созвониться быстрее будет?

**Comment by Nelfimov** [comment]
@Amiditin давай завтра с утра, пиши как будешь на связи

**Comment by Amiditin** [comment]
> давай завтра с утра, пиши как будешь на связи

Окей, тогда сейчас создам PR с изменениями в [/src](https://github.com/atls/tools/tree/master/code/code-format/src), которые по идее должны работать.

**Comment by Amiditin** [comment]
@Nelfimov обновил бандлы, и у меня заработал formatterIgnorePatterns, запросил ревью.

Также можешь ещё новых задачек повесить, или мб здесь ещё что-то можно сделать?
