### ISSUE TITLE
webpack upgrade

### ISSUE THREAD

**Issue by Nelfimov** [atls/tools#255]
### С чем связан запрос на фичу?

Необходимо прогрейдить версию `webpack` до 5 версии

### Расскажите как вы это себе видите

`webpack-chain` поддерживает только создание конфигурации для `webpack` версии 4. Поддержка 5-ой версии есть только в форках - https://github.com/neutrinojs/webpack-chain/pull/297.

Необходимо либо найти альтернативу либо использовать форком (нежелательно).

**Comment by Nelfimov** [comment]
- Конфигурацию `webpack` обновил для 5 версии
- Убрал использование `webpack-chain` - с 2020 нет обновлений и поддержки 5 версии
- Протестировал на своем репозитории: https://github.com/Nelfimov/odin-battleship/tree/test/yarn-webpack


## Тестирование проводил так:
- в `atls/tools`:
  - билд `@atls/code-service`
  - билд `@atls/code-service-worker`
  - билд нового `yarn` бандла
- в тестируемом репозитории подключил наш `yarn`
- подключил `@atls/code-service`
- запустил `yarn service build`
- проверил наличие всех импортированных ассетов в билде (шрифты, картинки, иконки)
- сравнил с `old_dist` - билд с использованием старого вебпака из пет проекта

## Что заметил

Билд что с текущим `yarn` и `@atls/code-service` что с рефактором производит один и тот же бандл - шрифты включаются.

@TorinAsakura стоит ли тогда "трогать, если работает"?

Ошибка с шрифтами в наших проектах связана с тем, что `injectFontFaces` была неправильно написана. Для этого в `hyperion` обновил инструкцию и протестировал. Конфигурация нашего вебпака на вывод не влияет - next использует свой вебпак + swc.

**Comment by TorinAsakura** [comment]
@Nelfimov Переход на 5-й вебпак так или иначе неизбежен, ведь мы стремимся к микрофронтам, а без 5-о вебпака их не реализовать через федерации

**Comment by TorinAsakura** [comment]
@Nelfimov На данной стадии, если это видится геморроем - можешь не трогать и оставить задачку для бэклога

**Comment by Nelfimov** [comment]
> @Nelfimov На данной стадии, если это видится геморроем - можешь не трогать и оставить задачку для бэклога

Конфиг переписан, сборка у обычных реакт приложений проходит успешно. Тестировал на репе выше.

Может еще где-то протестировать? Например, https://github.com/atls/reactjs/tree/master/packages/payment-widget

**Comment by atls-github** [comment]
Статус?

**Comment by Nelfimov** [comment]
Конфиг переписан нативными средствами.

Договорились изучить вопрос микро-фронтендов, через [`ModuleFederation`](https://webpack.js.org/plugins/module-federation-plugin)

**Comment by TorinAsakura** [comment]
Так чо с таской-то? Закрываем? Или чего?

**Comment by Nelfimov** [comment]
Я планирую сделать тестовую репу с микро фронтами для проверки конфига.

**Comment by TorinAsakura** [comment]
> Я планирую сделать тестовую репу с микро фронтами для проверки конфига.

У нас есть прожект-стартер - вполне можно там обкатать, двойную пользу сделаем

**Comment by atls-github** [comment]
Статус?

**Comment by atls-github** [comment]
Таске месяц. Закрыта за утратой актуальности.
