### ISSUE TITLE
Грейд `yarn` `typescript`

### ISSUE THREAD

**Issue by Nelfimov** [atls/tools#263]
### С чем связан запрос на фичу?

Необходимо перейти на последнюю версию `typescript`

### Расскажите как вы это себе видите

- [x] Грейдим по проекту `yarn-pkg` до последней версии
- [x] Создаем бандл `yarn`
- [x] В любом проекте запускаем наши стандартные скрипты (`check`, `image`, `build`)
- [x] При ошибке в любом из скриптов - смотрим ошибку, разбираемся, повторяем
- [x] Грейд `nodejs` до последней LTS - 20.9.0
- [x] `schematic` - посмотреть нужен ли?

**Comment by TorinAsakura** [comment]
я бы на твоём месте вынес это в отдельные таски, а эту сделал родительской
