### ISSUE TITLE
Добавить плагин для фиксации версий зависимостей

### ISSUE THREAD

**Issue by Nelfimov** [atls/tools#281]
### С чем связан запрос на фичу?

В проектах могут встречаться не фиксированные версии зависимостей - `^`, `*` и т.д. Это может сломать наши инструменты при будущих обновлениях. Чтобы этого избежать и автоматизировать процесс надо добавить плагин для фиксации версий.

### Расскажите как вы это себе видите

- [ ] минимум: рассмотреть плагин ниже, протестировать в наших проектах
- [ ] максимум: написать свой плагин

### Приложите пример реализаций

https://github.com/splitgraph/yarn-plugin-pin-deps

**Comment by TorinAsakura** [comment]
> ### С чем связан запрос на фичу?
> В проектах могут встречаться не фиксированные версии зависимостей - `^`, `*` и т.д. Это может сломать наши инструменты при будущих обновлениях. Чтобы этого избежать и автоматизировать процесс надо добавить плагин для фиксации версий.
> 
> ### Расскажите как вы это себе видите
> * [ ]  минимум: рассмотреть плагин ниже, протестировать в наших проектах
> * [ ]  максимум: написать свой плагин
> 
> ### Приложите пример реализаций
> https://github.com/splitgraph/yarn-plugin-pin-deps

можешь сделать частью преттира
